version: '3.8'

services:
  app:
    build: .
    container_name: legok_backend
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT:-3000}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME:-perbasikuningan}
      - DB_PORT=${DB_PORT:-3306}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
      - AES_IV_LENGTH=${AES_IV_LENGTH:-16}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./uploads:/app/uploads